name: Setup cross-build
description: build ci for rust.
author: ahaoboy
branding:
  icon: play-circle
  color: white

inputs:
  bin:
    description: "bin"
    required: false
  target:
    description: "target"
    required: false
  GITHUB_TOKEN:
    description: "GITHUB_TOKEN"
    required: false
  RUSTFLAGS:
    description: "RUSTFLAGS"
    required: false
  tag:
    description: "tag"
    required: false
  makeLatest:
    description: "makeLatest"
    required: false
  allowUpdates:
    description: "allowUpdates"
    required: false
  features:
    description: "features"
    required: false
  toolchain:
    description: "toolchain"
    required: false
    default: "stable"
  archive:
    description: "archive"
    required: false
    # default: "$bin-$target"
runs:
  using: "composite"
  steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        rustflags: ${{ inputs.rustflags }}
        toolchain: ${{ inputs.toolchain }}

    - name: Setup musl aarch64
      if: startsWith(inputs.target, 'aarch64-unknown-linux')
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          curl \
          libc6-arm64-cross \
          libc6-dev-arm64-cross \
          crossbuild-essential-arm64 \
          clang \
          qemu-system-arm \
          qemu-efi-aarch64 \
          qemu-utils \
          qemu-user

        curl -L https://github.com/ahaoboy/aarch64-linux-musl-cross-build/releases/latest/download/aarch64-linux-musl-cross.tgz | tar xzf -
        sudo mv aarch64-linux-musl-cross /musl

        echo "CC_aarch64_unknown_linux_musl=aarch64-linux-musl-gcc" >> $GITHUB_ENV
        echo "CXX_aarch64_unknown_linux_musl=aarch64-linux-musl-g++" >> $GITHUB_ENV
        echo "AR_aarch64_unknown_linux_musl=aarch64-linux-musl-ar" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-musl-gcc" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUNNER=qemu-aarch64" >> $GITHUB_ENV

        echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++" >> $GITHUB_ENV
        echo "AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUNNER=qemu-aarch64" >> $GITHUB_ENV

        echo "LD_LIBRARY_PATH=/usr/aarch64-linux-gnu/lib" >> $GITHUB_ENV

        sudo ln -s /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 /lib/ld-linux-aarch64.so.1

        mkdir -p ~/.cargo/
        echo "[target.aarch64-unknown-linux-musl]" >> ~/.cargo/config.toml
        echo 'rustflags = ["-C", "link-self-contained=yes","-C", "linker=rust-lld"]' >> ~/.cargo/config.toml
        echo "[target.aarch64-unknown-linux-gnu]" >> ~/.cargo/config.toml
        echo 'rustflags = ["-C", "linker=aarch64-linux-gnu-gcc"]' >> ~/.cargo/config.toml

        echo "/musl/bin" >> $GITHUB_PATH

    - name: install cross
      shell: bash
      run: |
        cargo install -q cross --git https://github.com/cross-rs/cross
        cargo clean

    - uses: taiki-e/upload-rust-binary-action@v1
      with:
        dry-run: true
        bin: ${{ inputs.bin }}
        target: ${{ inputs.target }}
        token: ${{ inputs.GITHUB_TOKEN }}
        features: ${{ inputs.features }}
        archive: ${{ inputs.archive }}
        ref: "refs/tags/dummy"
      env:
        RUSTFLAGS: ${{ inputs.RUSTFLAGS }}
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.archive || format('{0}-{1}', inputs.bin, inputs.target) }}
        path: ${{ format('{0}.*', (inputs.archive || format('{0}-{1}', inputs.bin, inputs.target))) }}
        # name: ${{ inputs.archive != '' && inputs.archive || format('{0}-{1}', inputs.bin, inputs.target) }}
        # path: ${{ inputs.archive != '' && format('{0}.*', inputs.archive) || format('{0}-{1}.*', inputs.bin, inputs.target) }}
    - name: release nightly
      uses: ncipollo/release-action@v1
      if: ${{ inputs.tag != '' }}
      with:
        tag: ${{ inputs.tag }}
        artifacts: ${{ format('{0}.*', (inputs.archive || format('{0}-{1}', inputs.bin, inputs.target))) }}
        # path: ${{ inputs.archive != '' && format('{0}.*', inputs.archive) || format('{0}-{1}.*', inputs.bin, inputs.target) }}
        allowUpdates: ${{ inputs.allowUpdates }}
        makeLatest: ${{ inputs.makeLatest }}
        token: ${{ inputs.GITHUB_TOKEN }}
